name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]
  workflow_dispatch:    # ручной запуск

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '24.18.1'
          cache: 'npm'
      
      - run: npm ci
      - run: npm run build-only
      
      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist/  # или build/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/deploy-pages@v4
